INSERT INTO activity (activity_en, activity_ru, status, kind_id)
VALUES ('общий зал', 'general hall', 1, 1),
       ('настольный теннис', 'table tennis', 1, 1),
       ('боксерский ринг', 'boxing ring', 1, 1),
       ('кардио зона', 'cardio zone', 1, 1),
       ('общий бассейн', 'general pool', 1, 2),
       ('детский бассейн', 'children\'s swimming pool', 1, 2),
('джакузи', 'hot tub', 1, 2),
('сауна', 'sauna', 1, 3),
('массаж', 'massage', 1, 3),
('спортивный бар', 'sports bar', 1, 3),
('йога', 'yoga', 1, 4),
('зумба', 'zumba', 1, 4),
('фитнес', 'fitness', 1, 4),
('пилатэс', 'pilates', 1, 4);
